### ISSUE TITLE
Tweet Generator Project Check in 

### ISSUE THREAD

**Issue by Sukhrobjon** [kevin-meyers/tweet-generator#1]
**Random dictionary words:**
- It would be better to use calculating the length of the dictionary instead of using a fixed number
- If you add if statement in your main function to check the args in the terminal

**Histogram:**
- I don't think you need a Node class to create Histogram class
- Dont forget to add comments for complex lines of code or docstring for the function

**Sample words by frequency:**
- I couldn’t run the file, make sure to include the
- Add docstrings to your functions  some of them seems too complicated to understand 

**Web application**  
- Make sure you are using right syntax when you call an external function from other files

**Markov chain**
- Add docstrings to your functions  some of them seems too complicated to understand 
- Add comments to explain the complex lines e.g. line 29 in your  Markov chain class 
```self._word_pointers = KeyDefaultDict(lambda x: self._new_word(x))```
- Don't forget to close the file in your read_file() function on line 40, don't forget to have return statement for your list of words

**Comment by kevin-meyers** [comment]
**Random Dictionary Words**:
I put that there as a placeholder since I couldnt think of a good way to do it without looping over the entire dictionary, where my way only gets lines generated by random.random() * len.
I was actually thinking in a real implementation like that I would put the length of the dictionary as the first line or something, I'll make a comment.

**Histogram:**
I did it the normal way, code improvement on that way to come. I'm also thinking about using a named tuple instead of a histnode like you said.

**Web App:**
Still down, works locally but heroku wont print any logs at all, will have to debug hard later.

**Markov Chain:**
Rewrote using normal stuff, the .import at the bottom is because it moved heroku forward a bit.
